name: movies_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  get_it: ^7.2.0
  internet_connection_checker: ^1.0.0+1
  cached_network_image: ^3.2.2
  mockito: ^5.3.2
  dio: ^5.3.3
  injectable: ^2.3.2
  http_mock_adapter: ^0.6.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  injectable_generator:  
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
  assets:
    - assets/images/
    - .env
  uses-material-design: true
